# Generated by Django 2.1 on 2018-08-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='prompt描述')),
                ('private', models.BooleanField(default=False, verbose_name='私有')),
                ('replace', models.TextField()),
                ('data', models.TextField(verbose_name='常规模式数据')),
                ('simple_data', models.TextField(verbose_name='简单模式数据')),
                ('show_hmi', models.BooleanField(default=False, verbose_name='显示界面')),
                ('play_beep', models.BooleanField(default=False, verbose_name='播放BEEP音')),
                ('can_omit', models.BooleanField(default=True)),
                ('barge_in', models.BooleanField(default=True)),
                ('async', models.BooleanField(default=True)),
                ('_type', models.IntegerField(default=2)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompts.Program')),
            ],
        ),
    ]
