# Generated by Django 2.1 on 2018-08-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='prompt名'),
            preserve_default=False,
        ),
    ]
